# Project Information
site_name: WealthAccess
site_description: Python wrapper for WealthAccess API
site_author: Doug Guthrie

# Configuration
theme:
    name: material
    palette:
        primary: indigo
        scheme: slate
    language: en

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

# Nav
nav:
    - "Home": index.md
    - "Functions":
        - functions/advisor.md
        - functions/firm.md
        - functions/investors.md
    - "Classes":
        - classes/advisor.md
        - classes/firm.md
        - classes/investors.md
    